# install-services.yml
---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing services
        apt:
          name: apache2
          state: present

  - hosts: webservers
    become: true
    tasks:
      - name: Installing Apache
        apt:
          name: apache2
          state: present
